version: '3'
services:
    react-docker: 
      restart: always
      build:  
        context: .
        dockerfile:  dockerfile.dev
      ports:
        -  "3003:3000"
      volumes:
        - .:/app